# Generated by Django 3.1.7 on 2021-04-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210403_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'student'), ('company', 'company'), ('admin', 'admin')], default='student', max_length=100),
        ),
    ]
