# Generated by Django 3.1.7 on 2021-04-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_resume_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='resume_active',
        ),
    ]
