# Generated by Django 3.1.7 on 2021-04-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_customuser_resume_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='resume_active',
            field=models.BooleanField(default=False),
        ),
    ]
