# Generated by Django 3.1.7 on 2021-04-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customuser_resume_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='resume_active',
            field=models.BooleanField(default=True),
        ),
    ]
