# Generated by Django 3.1.7 on 2021-04-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210410_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='resume_active',
        ),
    ]
