# Generated by Django 3.1.7 on 2021-04-27 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210427_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='sun_forum',
            new_name='sub_forum',
        ),
    ]
