# Generated by Django 3.1.7 on 2021-04-12 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=70)),
                ('preview', models.TextField()),
                ('about', models.TextField()),
                ('website', models.URLField(max_length=250)),
                ('service_provided', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('headquaters', models.CharField(max_length=250)),
                ('type_of_company', models.CharField(choices=[('public', 'Publicly held'), ('private', 'Privately held')], max_length=50)),
                ('founded_on', models.CharField(max_length=4)),
                ('specialty', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
