# Generated by Django 3.1.7 on 2021-04-17 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0005_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selected',
            name='applicant',
        ),
        migrations.AddField(
            model_name='selected',
            name='selected_applicants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
