# Generated by Django 3.1.7 on 2021-04-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20210417_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hide_key',
            field=models.BooleanField(default=False),
        ),
    ]
