# Generated by Django 3.1.7 on 2021-04-09 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=10)),
                ('email2', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('college', models.CharField(default='Pillai College Of Engineering', max_length=70)),
                ('ssc', models.CharField(max_length=5)),
                ('hsc', models.CharField(max_length=5)),
                ('sem1', models.CharField(max_length=4)),
                ('sem2', models.CharField(max_length=4)),
                ('sem3', models.CharField(max_length=4)),
                ('sem4', models.CharField(max_length=4)),
                ('sem5', models.CharField(max_length=4)),
                ('sem6', models.CharField(max_length=4)),
                ('sem7', models.CharField(max_length=4)),
                ('sem8', models.CharField(max_length=4)),
                ('career_obj', models.TextField()),
                ('linkden_url', models.CharField(max_length=100, null=True)),
                ('github_url', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
