# Generated by Django 3.1.7 on 2021-04-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresume',
            name='sem7',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='sem8',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
