# Generated by Django 3.1.7 on 2021-04-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210410_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresume',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Prefer Not to Say', 'Other')], max_length=20),
        ),
    ]
