# Generated by Django 3.1.7 on 2021-04-10 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0005_auto_20210410_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresume',
            old_name='hsc',
            new_name='hsc_diploma',
        ),
        migrations.CreateModel(
            name='SkillList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=125)),
                ('skill_type', models.CharField(max_length=50)),
                ('skill_level', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
