# Generated by Django 3.1.7 on 2021-04-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210410_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllist',
            name='skill_level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('InterMediate', 'Intermediate'), ('Advance', 'Advance')], max_length=25),
        ),
    ]
