# Generated by Django 3.1.7 on 2021-04-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210410_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresume',
            name='resume_active',
            field=models.BooleanField(default=False),
        ),
    ]
