# Generated by Django 3.1.7 on 2021-04-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_studentresume_resume_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresume',
            name='resume_active',
        ),
    ]
