# Generated by Django 3.1.7 on 2021-04-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_studentresume_resume_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresume',
            name='college',
            field=models.CharField(default='Pillai College Of Engineering', max_length=200),
        ),
    ]
