# Generated by Django 3.1.7 on 2021-04-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20210412_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlist',
            name='Semester',
        ),
        migrations.AddField(
            model_name='projectlist',
            name='semester',
            field=models.CharField(choices=[('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VII')], default='3', max_length=3),
        ),
    ]
