# Generated by Django 3.1.7 on 2021-04-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20210412_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresume',
            name='branch',
            field=models.CharField(choices=[('CE', 'Computer Engineering'), ('IT', 'Information Technology'), ('AE', 'Automobile Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CHE', 'Chemical Engineering'), ('EXTC', 'Electronics And Telecommunication'), ('ERTX', 'Electronics Engineering')], default='', max_length=20),
        ),
    ]
