# Generated by Django 3.1.7 on 2021-04-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20210413_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresume',
            name='branch',
            field=models.CharField(choices=[('Computer Engineering', 'Computer Engineering'), ('Information Technology', 'Information Technology'), ('Automobile Engineering', 'Automobile Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Electronics And Telecommunication', 'Electronics And Telecommunication'), ('Electronics Engineering', 'Electronics Engineering')], max_length=300),
        ),
    ]
