# Generated by Django 3.1.7 on 2021-04-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20210413_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresume',
            old_name='hsc_diploma',
            new_name='hsc',
        ),
    ]
