# Generated by Django 3.1.7 on 2021-04-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20210421_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresume',
            name='diploma',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='diploma_college',
            field=models.CharField(default='Ryan International School', max_length=200),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='hsc_college',
            field=models.CharField(default='Ryan International School', max_length=200),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='ssc_college',
            field=models.CharField(default='Ryan International School', max_length=200),
        ),
    ]
