# Generated by Django 3.1.7 on 2021-04-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20210421_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresume',
            name='diploma_college',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='hsc_college',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
