# Generated by Django 3.1.7 on 2021-05-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20210423_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresume',
            name='Backlogs',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='addmission_no',
            field=models.CharField(default=0, max_length=11),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='attendance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
