# Generated by Django 3.1.7 on 2021-05-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20210511_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresume',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
