# Generated by Django 3.1.7 on 2021-04-25 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='Pillai College Of Engineering', max_length=220)),
                ('topic', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('organized_by', models.CharField(max_length=200)),
                ('students_eligible', models.TextField()),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
