# Generated by Django 3.1.7 on 2021-04-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='hide_key',
            field=models.BooleanField(default='False'),
        ),
    ]
