# Generated by Django 3.1.7 on 2021-04-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_notice_hide_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='hide_key',
            field=models.BooleanField(default=False),
        ),
    ]
