# Generated by Django 3.1.7 on 2021-05-12 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20210511_2103'),
        ('manager', '0003_auto_20210427_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='changesNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('is_notified', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.studentresume')),
            ],
        ),
    ]
