# Generated by Django 3.1.7 on 2021-05-12 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20210511_2103'),
        ('manager', '0004_changesnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changesnote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentresume'),
        ),
    ]
